//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthorBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookAuthor
    {
        public int AuthorBookID { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public Nullable<int> BookID { get; set; }
        public string Active { get; set; }
        public string SoftDelete { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Book Book { get; set; }
    }
}
